### ISSUE TITLE
Array default values

### ISSUE THREAD

**Issue by omsk359** [michaelcontento/redux-storage#103] opened 2016-02-28 03:32 UTC
Hi! I have a test reducer:
`myReducer = (state = { arr: [1, 2, 3] }, action) => action.type == 'TEST' ? { arr: [5] } : state`
It's save to store correctly after dispatch: `{ arr: 5 }`
But after load it's has a value `{ arr: [5, 2, 3] }`.
Lo-dash `_.merge` problem.

**Comment by michaelcontento** [comment] 2016-02-29 09:37
Hi! Could you provide me some example code?

I've tried to [reproduce this problem](https://github.com/michaelcontento/redux-storage/commit/76f464701de6c760a52c3285dedad3e59183e7f2) but with no success. For me everything looks and behaves as is should ...

**Comment by omsk359** [comment] 2016-03-01 00:14
Maybe I use it wrong, but
1. Page load, reducer init: `arr = [1, 2, 3]`
2. redux-storage load nothing: `arr = [1, 2, 3]`
3. dispatch: `arr = [5]`
4. Reload page, reducer init: `arr = [1, 2, 3]`
5. redux-storage load: `arr = [5, 2, 3]`

**Comment by michaelcontento** [comment] 2016-03-01 06:57
Hm .. strange. Would it be possible for you to inspect the state of the engine right BEFORE you trigger the load action? This depends on the engine in use but for [redux-storage-engine-localstorage](https://github.com/michaelcontento/redux-storage-engine-localstorage) the output of:

```js
console.log(store.getState());
console.log(localStorage.getItem(key));
```

would be very interesting!

**Comment by omsk359** [comment] 2016-03-01 11:14
Ok. It's my [store.js](https://github.com/omsk359/issues/blob/master/redux-storage/store.js) now.
0. I open page and run `clearStorage()`
1. Reload page. My out: 

> before1: [1, 2, 3]
> before2: null
> [13:54:46] [Dispatching] {"type":"REDUX_STORAGE_LOAD","payload":{}}
> [13:54:46] [Store] {"myReducer":{"arr":[1,2,3]}}
> Loaded state: undefined
> after1: [1, 2, 3]
> after2: null

2. I execute `store.dispatch({type: 'TEST'})`
3. Reload page again:

> before1: [1, 2, 3]
> before2: {"myReducer":{"arr":[5]}}
> [13:55:39] [Dispatching] {"type":"REDUX_STORAGE_LOAD","payload":{"myReducer":{"arr":[5]}}}
> [13:55:39] [Store] {"myReducer":{"arr":[5,2,3]}}
> Loaded state: [5]
> after1: [5, 2, 3]
> after2: {"myReducer":{"arr":[5]}}

**Comment by michaelcontento** [comment] 2016-03-01 16:00
Could you also please paste the result of `npm list` so that I can see the used versions of all involved libraries? I still have no clue whats the root cause of this :( 

And a last question: in which browsers have you tested this?

**Comment by omsk359** [comment] 2016-03-02 07:41
I use Meteor 1.2.1, it's [`meteor list`](https://github.com/omsk359/issues/blob/master/redux-storage/meteor_list.txt) out and [packages.json](https://github.com/omsk359/issues/blob/master/redux-storage/packages.json) file used by meteorhacks:npm.
Browser: Chrome 48.

I was not paying a lot of time, but quickly looked at your code. Are you use lodash `merge` function after action Load? If so, it may be the cause because
`_.isEqual(_.merge([1,2,3], [5]), [5,2,3]) // true`

**Comment by michaelcontento** [comment] 2016-04-28 07:59
[redux-storage-merger-simple](https://github.com/michaelcontento/redux-storage-merger-simple) is the default merger used by redux-storage. Please have a look at it and create a issue there with some code to reproduce this issue.

I'm closing this issue here now, as a) it's no longer related to the code in this repository and b) I'm still unable to reproduce this :(

**Closed by michaelcontento** 2016-04-28 07:59 UTC
Labels: waiting for feedback
